# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - CXXFLAGS="-O2 -pedantic -Wall -Wextra -Wno-c++0x-compat -Wno-long-long -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas"
    - OMP_NUM_THREADS=4

before_install:
  - sudo apt-get update -qq

# Install cmake cppcheck
install:
  - sudo apt-get install -y cmake cppcheck

# Download and install Boost C++ libraries
before_script:
  - wget https://vorboss.dl.sourceforge.net/project/boost/boost/1.62.0/boost_1_62_0.tar.gz
  - tar xvf boost_1_62_0.tar.gz && rm boost_1_62_0.tar.gz
  - mv boost_1_62_0/boost include
  - rm -rf boost_1_62_0

# Run primecount tests
script:
  - cmake .
  - make -j4
  - ldd primesum
  - cppcheck src include --error-exitcode=1 -i$(cd primesieve-*; basename $(pwd))
  - ./primesum --test
