# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - CXXFLAGS="-O2 -pedantic -Wall -Wextra -Werror -Wno-missing-braces -Wno-long-long -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas"
    - OMP_NUM_THREADS=4

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y g++-5 make cmake cppcheck valgrind
  - sudo rm -f /usr/bin/g++
  - sudo ln -s /usr/bin/g++-5 /usr/bin/g++

# Run cmake
before_script:
  - if [ "$CXX" = "g++" ]; then cmake .; fi
  - if [ "$CXX" = "clang++" ]; then cmake . -DWITH_OPENMP=OFF; fi
  - make -j4
  - ldd primesum
  - cppcheck src include --error-exitcode=1 -ilib

# Run primesum tests
script:
  - ./primesum --test
  - valgrind --error-exitcode=1 ./primesum 1e14
