# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp
dist: xenial

compiler:
  - gcc
  - clang

env:
  global:
    - CXXFLAGS="-O2 -pedantic -Wall -Wextra -Werror -Wno-missing-braces -Wno-long-long"
    - OMP_NUM_THREADS=4

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y make cmake cppcheck valgrind mingw-w64

script:
  # 1) Static code analysis
  - cppcheck src include --error-exitcode=1
  # 2) Run test suite
  - mkdir build
  - cd build
  - if [ "$CXX" = "g++" ]; then cmake ..; fi
  - if [ "$CXX" = "clang++" ]; then cmake .. -DWITH_OPENMP=OFF; fi
  - make -j4
  - ldd primesum
  - ./primesum --test
  # 3) Runtime memory analysis
  - valgrind --error-exitcode=1 ./primesum 1e14
  # 4) Compile using MinGW
  - cd ..
  - rm -rf build
  - mkdir build
  - cd build
  - |
    cmake .. -DCMAKE_SYSTEM_NAME=Windows \
             -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++-posix \
             -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
             -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
  - make -j4 VERBOSE=1
