# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - CXXFLAGS="-O2 -pedantic -Wall -Wextra -Werror -Wno-long-long -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas"
    - OMP_NUM_THREADS=4

before_install:
  - sudo apt-get update -qq

# Install cmake cppcheck
install:
  - sudo apt-get install -y cmake cppcheck

# Test build.sh script
before_script:
  - if [ "$CXX" = "g++" ]; then cmake .; fi
  - if [ "$CXX" = "clang++" ]; then cmake . -DOpenMP_CXX_FLAGS=""; fi
  - make -j4
  - ldd primesum
  - cppcheck src include --error-exitcode=1 -isrc/primesieve

# Run primecount tests
script:
  - ./primesum --test
