# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - CXXFLAGS="-O2 -pedantic -Wall -Wextra -Werror -Wno-long-long -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas"
    - OMP_NUM_THREADS=4

before_install:
  - sudo apt-get update -qq

# Install cmake cppcheck
install:
  - sudo apt-get install -y cmake cppcheck

# Test build.sh script
before_script:
  - cmake .
  - make -j4
  - ldd primecount
  - cppcheck src include --error-exitcode=1 -i$(cd primesieve-*; basename $(pwd))

# Run primecount tests
script:
  - ./primesum --test
