# Automated testing using appveyor.com
# https://ci.appveyor.com/projects

version: 1.0.{build}

image:
- Ubuntu
- Ubuntu2004
- macos

branches:
  except:
    - gh-pages

platform:
  - x64

configuration:
  - Debug
  - Release

for:
  # Test using GCC sanitizers
  - matrix:
      only:
        - image: Ubuntu
          platform: x64
          configuration: Debug
    environment:
      CFLAGS: "-Wall -Wextra -pedantic -Werror -Wno-long-long -Wno-missing-braces -O1 -g -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all -fno-omit-frame-pointer"
      CXXFLAGS: "-Wall -Wextra -pedantic -Werror -Wno-long-long -Wno-missing-braces -O1 -g -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all -fno-omit-frame-pointer"
    build_script:
      - cmake . -DCMAKE_BUILD_TYPE=$Configuration
      - make VERBOSE=1
    test_script:
      - ./primesum --test

  - matrix:
      only:
        - image: Ubuntu
          platform: x64
          configuration: Release
    environment:
      CFLAGS: "-Wall -Wextra -pedantic -Werror -Wno-long-long -Wno-missing-braces"
      CXXFLAGS: "-Wall -Wextra -pedantic -Werror -Wno-long-long -Wno-missing-braces"
    build_script:
      - cmake . -DCMAKE_BUILD_TYPE=$Configuration -DCMAKE_INSTALL_PREFIX=$(pwd)
      - make VERBOSE=1
      - make install
    test_script:
      - ./primesum --test

  - matrix:
      only:
        - image: macos
          platform: x64
    environment:
      CFLAGS: "-Wall -Wextra -pedantic -Werror -Wno-long-long -Wno-missing-braces"
      CXXFLAGS: "-Wall -Wextra -pedantic -Werror -Wno-long-long -Wno-missing-braces"
    build_script:
      - cmake . -DCMAKE_BUILD_TYPE=$Configuration -DCMAKE_INSTALL_PREFIX=$(pwd)
      - make VERBOSE=1
      - make install
    test_script:
      - ./primesum --test
